# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 013174519acf9e785bf24ac6b9016c12d6a09d5d76c3ac5cd54a753baa9aeaa694b9269d8ef368f244c0b71c3277c051fcf10c1c48e447a84260536d5c201c74

test:
  secret_key_base: 351626522da230c942ef3dc31780825cbd42f72909a0ea0f127e728da5f63e67e63c4126162de45329c04e59709d9454f59f42c5fe99934c2557eba4055c7c9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
